sudo: required

git:
  submodules: false  

addons:
  apt:
    sources:
      - sourceline: "deb http://apt.llvm.org/precise/ llvm-toolchain-precise-3.8 main"
        key_url : "http://apt.llvm.org/llvm-snapshot.gpg.key"
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - g++-6
      - clang-3.8
      - llvm-dev
      - cmake
      - cmake-data
      
language: cpp

compiler:
  - gcc
  - clang

os:
  - linux
  - osx
  
osx_image: xcode8
  
script: ./.travis/build.sh
after_success: ./.travis/signature.sh

env:
  - build_type=debug static_libraries=FALSE
  - build_type=release static_libraries=FALSE
  - build_type=debug static_libraries=TRUE
  - build_type=release static_libraries=TRUE

matrix:
  include:
    - os: linux
      compiler: gcc
      env: build_type=coverage static_libraries=FALSE
    - os: linux
      compiler: clang
      env:
        build_type=debug static_libraries=FALSE
        appended_flags="-fsanitize=address;-fno-omit-frame-pointer"
    - os: linux
      compiler: clang
      env:
        build_type=debug static_libraries=FALSE
        appended_flags="-fsanitize=undefined;-fsanitize=integer;-fno-omit-frame-pointer"
